# Generated by Django 4.1 on 2024-03-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo1',
            name='address',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='contactinfo1',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='teachearinfo1',
            name='subject',
            field=models.CharField(max_length=60),
        ),
    ]
